const colors = {
  light: {
    text: "#0A0A0F",
    tint: "#00D4FF",
    background: "#F5F5FA",
    foreground: "#0A0A0F",
    card: "#FFFFFF",
    cardForeground: "#0A0A0F",
    primary: "#00AACC",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#1A1A3E",
    muted: "#F0F0F5",
    mutedForeground: "#8888AA",
    accent: "#7B61FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0EE",
    input: "#E0E0EE",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#0A0A0F",
    foreground: "#FFFFFF",
    card: "#131320",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#0A0A0F",
    secondary: "#1A1A2E",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1E2E",
    mutedForeground: "#8888AA",
    accent: "#7B61FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#252535",
    input: "#252535",
  },
  radius: 16,
};

export default colors;
